In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Read and examine the Data

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/arielb30/datasets/main/diamonds.csv')
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [ ]:
X = df.drop(['price'],axis=1)
y = df['price']
print("start: ",X.shape, y.shape)

start:  (53940, 9) (53940,)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20, random_state = 42)
print("train: ", X_train.shape, y_train.shape)
print("test:  " , X_test.shape, y_test.shape)

train:  (43152, 9) (43152,)
test:   (10788, 9) (10788,)

In [ ]:
dftrain = pd.concat([X_train,y_train],axis=1)
dftrain.head()

       carat        cut color clarity  depth  table     x     y     z  price
26546   2.01       Good     F     SI2   58.1   64.0  8.23  8.19  4.77  16231
9159    1.01  Very Good     E     SI2   60.0   60.0  6.57  6.49  3.92   4540
14131   1.10    Premium     H     VS2   62.5   58.0  6.59  6.54  4.10   5729
15757   1.50       Good     E     SI2   61.5   65.0  7.21  7.17  4.42   6300
24632   1.52  Very Good     G     VS1   62.1   57.0  7.27  7.32  4.53  12968

In [ ]:
# Group by 'cut' and calculate the mean of 'price'
cut_price_mean = dftrain.groupby('cut')['price'].mean().sort_values(ascending=True)
cut_price_mean

cut
Ideal        3470.103019
Good         3965.815736
Very Good    3987.217938
Fair         4416.170196
Premium      4568.368827
Name: price, dtype: float64

In [ ]:
cut_price_mean.index

Index(['Ideal', 'Good', 'Very Good', 'Fair', 'Premium'], dtype='object', name='cut')

In [ ]:
X_train['cut']=X_train['cut'].map({'Ideal':0, 'Good':1, 'Very Good':2, 'Fair':3, 'Premium':4})
X_train.head()

       carat  cut color clarity  depth  table     x     y     z
26546   2.01    1     F     SI2   58.1   64.0  8.23  8.19  4.77
9159    1.01    2     E     SI2   60.0   60.0  6.57  6.49  3.92
14131   1.10    4     H     VS2   62.5   58.0  6.59  6.54  4.10
15757   1.50    1     E     SI2   61.5   65.0  7.21  7.17  4.42
24632   1.52    2     G     VS1   62.1   57.0  7.27  7.32  4.53

In [ ]:
X_test['cut']=X_test['cut'].map({'Ideal':0, 'Good':1, 'Very Good':2, 'Fair':3, 'Premium':4})
X_test.head()

       carat  cut color clarity  depth  table     x     y     z
1388    0.24    0     G    VVS1   62.1   56.0  3.97  4.00  2.47
50052   0.58    2     F    VVS2   60.0   57.0  5.44  5.42  3.26
41645   0.40    0     E    VVS2   62.1   55.0  4.76  4.74  2.95
42377   0.43    4     E    VVS2   60.8   57.0  4.92  4.89  2.98
17244   1.55    0     E     SI2   62.3   55.0  7.44  7.37  4.61