In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({'A':[11,11,13,14,13,13],
                   'B':[np.nan,22,23,24,np.nan,26],
                   'C':[31,32,33,34,np.nan,36],
                   'D':[41,42,43,44,45,np.nan],
                   'E':[51,52,53,54,55,np.nan]
                   })

In [ ]:
df

    A     B     C     D     E
0  11   NaN  31.0  41.0  51.0
1  11  22.0  32.0  42.0  52.0
2  13  23.0  33.0  43.0  53.0
3  14  24.0  34.0  44.0  54.0
4  13   NaN   NaN  45.0  55.0
5  13  26.0  36.0   NaN   NaN

In [ ]:
# put your code here

In [ ]:
# הסרת שורות עם ערכים חסרים

    A     B     C     D     E
1  11  22.0  32.0  42.0  52.0
2  13  23.0  33.0  43.0  53.0
3  14  24.0  34.0  44.0  54.0

In [ ]:
# put your code here

In [ ]:
# הסרת עמודות עם ערכים חסרים

    A
0  11
1  11
2  13
3  14
4  13
5  13

In [ ]:
# put your code here

In [ ]:
# הסר עמודות שאין להם לפחות 5 ערכים תקינים
# hint: use thresh parameter

    A     C     D     E
0  11  31.0  41.0  51.0
1  11  32.0  42.0  52.0
2  13  33.0  43.0  53.0
3  14  34.0  44.0  54.0
4  13   NaN  45.0  55.0
5  13  36.0   NaN   NaN

In [ ]:
df

    A     B     C     D     E
0  11   NaN  31.0  41.0  51.0
1  11  22.0  32.0  42.0  52.0
2  13  23.0  33.0  43.0  53.0
3  14  24.0  34.0  44.0  54.0
4  13   NaN   NaN  45.0  55.0
5  13  26.0  36.0   NaN   NaN

In [ ]:
# put your code here

In [ ]:
# fill * on missing values

    A     B     C     D     E
0  11     *  31.0  41.0  51.0
1  11  22.0  32.0  42.0  52.0
2  13  23.0  33.0  43.0  53.0
3  14  24.0  34.0  44.0  54.0
4  13     *     *  45.0  55.0
5  13  26.0  36.0     *     *

In [ ]:
# put your code here

In [ ]:
# fill * on missing values column B

0       *
1    22.0
2    23.0
3    24.0
4       *
5    26.0
Name: B, dtype: object

In [ ]:
# put your code here

In [ ]:
# שים במקום ערכים חסרים את הממוצע של הטור

    A      B     C     D     E
0  11  23.75  31.0  41.0  51.0
1  11  22.00  32.0  42.0  52.0
2  13  23.00  33.0  43.0  53.0
3  14  24.00  34.0  44.0  54.0
4  13  23.75  33.2  45.0  55.0
5  13  26.00  36.0  43.0  53.0

In [ ]:
df

    A     B     C     D     E
0  11   NaN  31.0  41.0  51.0
1  11  22.0  32.0  42.0  52.0
2  13  23.0  33.0  43.0  53.0
3  14  24.0  34.0  44.0  54.0
4  13   NaN   NaN  45.0  55.0
5  13  26.0  36.0   NaN   NaN

In [ ]:
# put your code here

In [ ]:
# Group and Sum by column A

       B     C     D      E
A
11  22.0  63.0  83.0  103.0
13  49.0  69.0  88.0  108.0
14  24.0  34.0  44.0   54.0

In [ ]:
# put your code here

In [ ]:
# Display unique values on column A

array([11, 13, 14])

In [ ]:
# put your code here

In [ ]:
# How many unique values on column A

3

In [ ]:
# put your code here

In [ ]:
# How many per group in column A (value_counts)

13    3
11    2
14    1
Name: A, dtype: int64

In [ ]:
# put your code here

In [ ]:
# find maximum in column B

26.0

In [ ]:
# put your code here

In [ ]:
#display column names

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [ ]:
# put your code here

In [ ]:
#sort according to values in column A

    A     B     C     D     E
0  11   NaN  31.0  41.0  51.0
1  11  22.0  32.0  42.0  52.0
2  13  23.0  33.0  43.0  53.0
4  13   NaN   NaN  45.0  55.0
5  13  26.0  36.0   NaN   NaN
3  14  24.0  34.0  44.0  54.0